### ISSUE TITLE
Hash value ommission from Ruby-3.1

### ISSUE THREAD

**Issue by fonji** [zenspider/codeclimate-flog#15]
Hash value omission was introduced with ruby 3.1 - [rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted](https://rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted)

And apparently it breaks flog:
```
ERROR: parsing ruby file example.rb
Racc::ParseError: example.rb:5 :: parse error on value "," (tCOMMA) at:
  /usr/local/lib/ruby/2.6.0/racc/parser.rb:528:in `on_error'
  /usr/local/bundle/gems/ruby_parser-3.13.1/lib/ruby_parser_extras.rb:1179:in `on_error'
  /usr/local/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /usr/local/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
  /usr/local/bundle/gems/ruby_parser-3.13.1/lib/ruby_parser_extras.rb:1086:in `block in process'
```

`example.rb` content:

```ruby
# frozen_string_literal: true

class Example
  def perform(id)
    Model.find_by!(id:, something: :else)
  end
end
```

This is also happens to the duplication engine (codeclimate/codeclimate-duplication#375)

Thanks

**Comment by fonji** [comment]
Updating ruby_parser may do the trick
https://github.com/seattlerb/ruby_parser/blob/master/History.rdoc

**Comment by mlinderman** [comment]
Thanks @fonji!  The Quality team at Code Climate is making a concerted effort to upgrade all plug-ins, since some have been neglected for a while.  I'll bump up codeclimate-flog's priority.  Please keep in touch with our [changelog](https://codeclimate.com/changelog) for updates.

**Comment by fonji** [comment]
Thanks @mlinderman, I'm glad to hear that! :smiley:

**Comment by dantevvp** [comment]
Hey @fonji ! A new version of `codeclimate-flog` is now up to support the latest `ruby_parser` version. Thanks for your contribution!

**Comment by fonji** [comment]
That's awesome! Thanks @dantevvp :heart:

**Comment by fonji** [comment]
Thanks for the shoutout in the changelog! :two_hearts: 
I set up the channel as `channel: flog-4-6-6`, but I still have problems with hash value ommissions.
Did I miss something?

**Comment by dantevvp** [comment]
Hey @fonji ! 

Are you having issues when using the CLI? Or is it when analysing PRs on Github? If it's the latter, there might have been a delay in the update. Try running your analyses again and if any other issues arise let me know!

**Comment by fonji** [comment]
Oh you're right! It was when analysing PRs on Github, I pushed again just now and got my issues back.
Sorry for the false positive, and thank you once again!
