### ISSUE TITLE
Squiggly Heredoc not supported

### ISSUE THREAD

**Issue by cgriego** [zenspider/codeclimate-flog#8]
I'm not sure if this is the right place to report this, but this is where I ended up after being referred a few times.

Running the flog engine on my code which uses the Ruby 2.3 "squiggly heredoc" syntax (<<~), those files fail to parse. It's because the engine is using ruby_parser 3.8.4, but that version doesn't support the syntax. ruby_parser 3.10.0 has added support and is released.

```ERROR: parsing ruby file <file-name>
Racc::ParseError: <file-name>:<line-number> :: parse error on value "<<" (tLSHFT) at:```

**Comment by zenspider** [comment]
This is not the right place, but honestly I'm not sure where the right place even is? You've filed on codeclimate/codeclimate and as far as I can tell that's the closest place to the real thing.

The REAL issue would be against ruby_parser and/or flog, which I believe already supports this, so really it's a matter of @codeclimate (@gdiggs maybe?) rebuilding and deploying.

As far as maintenance of this thing goes... this was under contract w/ codeclimate. They're free to take it over. Happy to transfer or add people to this project.

**Comment by maxjacobson** [comment]
Hi @zenspider! It may be simplest to transfer this repository to the [codeclimate-community](https://github.com/codeclimate-community/) org, where we can admin the repository. If you're interested in that, will you please add myself and @efueger as admins, and one of us will take care of transfering the repository and kicking off a rebuild of the codeclimate-flog engine?

**Comment by zenspider** [comment]
I've added you two as collaborators. You should have invites in your inboxen. Not sure about admin part but I think that's part of the package deal. We'll figure it out.

**Comment by maxjacobson** [comment]
@zenspider Thank you. That allowed us to merge PRs, which is helpful for now to resolve the bug report we got. It doesn't seem to give us the permission to transfer the repository, as I hoped, but we're going to do a little research to figure out how to do that and follow up about it later. Thanks for your patience and help!

**Comment by maxjacobson** [comment]
To anyone experiencing this issue: the bugfix was just merged, and will be released on codeclimate.com this week

**Comment by zenspider** [comment]
Looks like I can initiate the transfer to a user or org, and then the other side accepts. I will start one to codeclimate-community.

**Comment by zenspider** [comment]
Oh. hrm. No. I can transfer it to an org I can write to, or start to initiate the transfer to a person. Please advise how you'd like to do this.
